services:

    preferences.repository.goat_query:
        public: false
        class: MakinaCorpus\Preferences\Repository\GoatQueryPreferencesRepository
        # @todo make this configurable, allow table namespace configuration
        arguments: ["@goat.runner.default"]

    preferences.repository:
        alias: preferences.repository.goat_query

    MakinaCorpus\Preferences\PreferencesRepository:
        alias: preferences.repository

    preferences:
        public: true
        class: MakinaCorpus\Preferences\Domain\Repository\DefaultPreferences
        arguments: ["@preferences.repository", "@?preferences.schema"]

    MakinaCorpus\Preferences\Preferences:
        alias: preferences

    preferences.form_type.value:
        public: false
        class: MakinaCorpus\Preferences\Form\PreferenceValueType
        arguments: ["@preferences.repository", "@?preferences.schema"]
        tags: ["form.type"]

    MakinaCorpus\Preferences\Form\PreferenceValueType:
        alias: preferences.form_type.value

    preferences.env_var_processor:
        public: false
        class: MakinaCorpus\Preferences\DependencyInjection\PreferencesEnvVarProcessor
        arguments: ["@preferences"]
        tags: ["container.env_var_processor"]

    # Remove this and make different implementations for different buses:
    #  - messanger
    #  - corebus
    #  - goat
    preferences.handler:
        public: false
        class: MakinaCorpus\Preferences\Domain\Handler\PreferencesHandler
        arguments: ['@preferences.repository', '@?preferences.schema']
        # Those tags will help.
        tags: ['goat.message_handler', 'app.handler']
